---
apiVersion: v1
kind: Service
metadata:
  name: web-server2-sv-lb
spec:
  selector:
    app: web-server2
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

